/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.studentmanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class DeleteStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form DeleteStudentForm
     */
    public DeleteStudentForm() {
        initComponents();
        txtDBMSMarks.setEditable(false);
        txtNIC.setEditable(false);
        txtPRFMarks.setEditable(false);
        txtName.setEditable(false);
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnterStudentId = new javax.swing.JButton();
        lblPRFMarks = new javax.swing.JLabel();
        btnBackToHomePage = new javax.swing.JButton();
        txtEnterStudentID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        txtPRFMarks = new javax.swing.JTextField();
        lblDeleteStudentForm = new javax.swing.JLabel();
        lblDBMSMarks = new javax.swing.JLabel();
        lblNIC = new javax.swing.JLabel();
        txtDBMSMarks = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        btnDeleteStudentProfile = new javax.swing.JButton();
        btnEnterStudentId1 = new javax.swing.JButton();

        btnEnterStudentId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEnterStudentId.setText("Enter Student ID");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPRFMarks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPRFMarks.setText("PRF Marks");

        btnBackToHomePage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBackToHomePage.setText("Back To Home Page");
        btnBackToHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomePageActionPerformed(evt);
            }
        });

        txtEnterStudentID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEnterStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterStudentIDActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                txtNameComponentHidden(evt);
            }
        });

        txtNIC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtPRFMarks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPRFMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPRFMarksActionPerformed(evt);
            }
        });

        lblDeleteStudentForm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDeleteStudentForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDeleteStudentForm.setText("Delete Student Form");

        lblDBMSMarks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDBMSMarks.setText("DBMS Marks");

        lblNIC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNIC.setText("NIC");

        txtDBMSMarks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDBMSMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDBMSMarksActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setText("Name");

        btnDeleteStudentProfile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeleteStudentProfile.setText("Delete Student Profile");
        btnDeleteStudentProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentProfileActionPerformed(evt);
            }
        });

        btnEnterStudentId1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEnterStudentId1.setText("Enter Student ID");
        btnEnterStudentId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterStudentId1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDeleteStudentForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBackToHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnDeleteStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDBMSMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPRFMarks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPRFMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDBMSMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEnterStudentId1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEnterStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDeleteStudentForm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEnterStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnterStudentId1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPRFMarks, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lblPRFMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDBMSMarks, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lblDBMSMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackToHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnterStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterStudentIDActionPerformed

    private void txtNameComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtNameComponentHidden

    }//GEN-LAST:event_txtNameComponentHidden

    private void txtPRFMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPRFMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPRFMarksActionPerformed

    private void txtDBMSMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDBMSMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDBMSMarksActionPerformed

    private void btnBackToHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomePageActionPerformed
        dispose();
        new MainForm().setVisible(true);  
    }//GEN-LAST:event_btnBackToHomePageActionPerformed

    private void btnDeleteStudentProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentProfileActionPerformed
        String id=txtEnterStudentID.getText();
        
        boolean isDeleted=StudentCollection.getInstance().deleteStudent(id);
        
        if (isDeleted) {
            JOptionPane.showMessageDialog(this, id+"    Student Deleted...");
        }
    }//GEN-LAST:event_btnDeleteStudentProfileActionPerformed

    private void btnEnterStudentId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterStudentId1ActionPerformed
        String id=txtEnterStudentID.getText();
        
        Student student = StudentCollection.getInstance().searchStudent(id);   
        
        if(student==null){
             JOptionPane.showMessageDialog(this, "Not found");
         }else{
             txtName.setText(student.getName());
             txtPRFMarks.setText(student.getPrfMarks()+"");
             txtDBMSMarks.setText(student.getDbmsMarks()+"");
             txtNIC.setText(student.getNIC());
        }
    }//GEN-LAST:event_btnEnterStudentId1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToHomePage;
    private javax.swing.JButton btnDeleteStudentProfile;
    private javax.swing.JButton btnEnterStudentId;
    private javax.swing.JButton btnEnterStudentId1;
    private javax.swing.JLabel lblDBMSMarks;
    private javax.swing.JLabel lblDeleteStudentForm;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPRFMarks;
    private javax.swing.JTextField txtDBMSMarks;
    private javax.swing.JTextField txtEnterStudentID;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPRFMarks;
    // End of variables declaration//GEN-END:variables
}
