/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.studentmanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class UpdateStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStudentForm
     */
    public UpdateStudentForm() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDBMSMarks = new javax.swing.JLabel();
        lblNIC = new javax.swing.JLabel();
        txtDBMSMarks = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblPRFMarks = new javax.swing.JLabel();
        btnBackToHomePage = new javax.swing.JButton();
        txtEnterStudentID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        txtPRFMarks = new javax.swing.JTextField();
        lblUpdateStudentForm = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnEnterStudentId = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDBMSMarks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDBMSMarks.setText("DBMS Marks");

        lblNIC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNIC.setText("NIC");

        txtDBMSMarks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDBMSMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDBMSMarksActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setText("Name");

        lblPRFMarks.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPRFMarks.setText("PRF Marks");

        btnBackToHomePage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBackToHomePage.setText("Back To Home Page");
        btnBackToHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomePageActionPerformed(evt);
            }
        });

        txtEnterStudentID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEnterStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterStudentIDActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                txtNameComponentHidden(evt);
            }
        });

        txtNIC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtPRFMarks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPRFMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPRFMarksActionPerformed(evt);
            }
        });

        lblUpdateStudentForm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUpdateStudentForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateStudentForm.setText("Update Student Form");

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnEnterStudentId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEnterStudentId.setText("Enter Student ID");
        btnEnterStudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterStudentIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUpdateStudentForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDBMSMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPRFMarks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(txtNIC)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPRFMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDBMSMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 85, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnterStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEnterStudentID))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnBackToHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUpdateStudentForm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEnterStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnEnterStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPRFMarks, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lblPRFMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDBMSMarks, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lblDBMSMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackToHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDBMSMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDBMSMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDBMSMarksActionPerformed

    private void txtEnterStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterStudentIDActionPerformed

    private void txtNameComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtNameComponentHidden

    }//GEN-LAST:event_txtNameComponentHidden

    private void txtPRFMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPRFMarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPRFMarksActionPerformed

    private void btnBackToHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomePageActionPerformed
        dispose();
        new MainForm().setVisible(true);
    }//GEN-LAST:event_btnBackToHomePageActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String id=txtEnterStudentID.getText();
        int prfMarks = Integer.parseInt(txtPRFMarks.getText());
        String name=txtName.getText();
        String nic=txtNIC.getText();
        int dbmsMarks =Integer.parseInt(txtDBMSMarks.getText());
        
        
        Student student=new Student(id,name,prfMarks,dbmsMarks,nic);
        
        boolean isUpdated=StudentCollection.getInstance().updateStudent(student);
        
        if (isUpdated) {
            JOptionPane.showMessageDialog(this, "Updated Successfully...");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnEnterStudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterStudentIdActionPerformed
        
        String id=txtEnterStudentID.getText();
        
        Student student = StudentCollection.getInstance().searchStudent(id);   
        
        if(student==null){
             JOptionPane.showMessageDialog(this, "Not found");
         }else{
             txtName.setText(student.getName());
             txtPRFMarks.setText(student.getPrfMarks()+"");
             txtDBMSMarks.setText(student.getDbmsMarks()+"");
             txtNIC.setText(student.getNIC());
        }
    }//GEN-LAST:event_btnEnterStudentIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToHomePage;
    private javax.swing.JButton btnEnterStudentId;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblDBMSMarks;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPRFMarks;
    private javax.swing.JLabel lblUpdateStudentForm;
    private javax.swing.JTextField txtDBMSMarks;
    private javax.swing.JTextField txtEnterStudentID;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPRFMarks;
    // End of variables declaration//GEN-END:variables
}
